# Auto-assign configuration for Bleu.js project
# This file configures automatic assignment of pull requests and reviewers

# List of users to assign to pull requests
assignees:
  - pejmanhaghighatnia
  - helloblueai

# List of users to request reviews from
reviewers:
  - pejmanhaghighatnia
  - helloblueai

# Number of reviewers to request (0 = all reviewers)
reviewers_count: 1

# Set to true if you want to add the author to the assignees list
add_author: false

# Set to true if you want to skip the auto-assign for draft pull requests
skip_draft: true

# List of labels to add to pull requests
labels:
  - "needs-review"
  - "ci/cd"

# List of keywords that will trigger auto-assign
keywords:
  - "urgent"
  - "hotfix"
  - "security"
  - "critical"

# List of file patterns that will trigger auto-assign
file_patterns:
  - "src/quantum/**"
  - "src/ml/**"
  - "tests/**"
  - "docs/**"
  - ".github/workflows/**"

# List of branches that will trigger auto-assign
branches:
  - "main"
  - "develop"
  - "staging"

# Set to true if you want to add reviewers based on file changes
add_reviewers_based_on_files: true

# Map of file patterns to reviewers
file_reviewers:
  "src/quantum/**":
    - pejmanhaghighatnia
  "src/ml/**":
    - pejmanhaghighatnia
  "tests/**":
    - pejmanhaghighatnia
  "docs/**":
    - helloblueai
  ".github/workflows/**":
    - pejmanhaghighatnia
