FROM node:20

WORKDIR /usr/src/app

# Set environment variable for more detailed logs
ENV PNPM_LOG_LEVEL=debug

# Copy only the relevant files
COPY package*.json pnpm-workspace.yaml pnpm-lock.yaml ./

RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile

# Copy only the necessary files from frontend
COPY . .

EXPOSE 8080
CMD ["npm", "run", "serve"]
