# Use the official Node.js image.
FROM node:18

# Create and change to the app directory.
WORKDIR /app

# Copy application dependency manifests to the container image.
COPY package*.json ./

# Install production dependencies.
RUN npm install -g pnpm
RUN pnpm install

# Copy local code to the container image.
COPY . .

# Run the web service on container startup.
CMD [ "pnpm", "run", "serve" ]
