repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        types: [python, markdown, yaml, json, text]
    -   id: end-of-file-fixer
        types: [python, markdown, yaml, json, text]
    -   id: check-yaml
        types: [yaml]
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: check-ast
        types: [python]
    -   id: check-json
        types: [json]
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: check-case-conflict
    -   id: check-docstring-first
        types: [python]
    -   id: check-executables-have-shebangs
        types: [shell]

-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black
        language_version: python3.8
        args: [--line-length=88]
        types: [python]

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
        types: [python]

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-docstrings',
            'flake8-bugbear',
            'flake8-comprehensions',
            'flake8-simplify',
            'flake8-unused-arguments',
            'flake8-return',
            'flake8-print',
            'flake8-import-order',
            'flake8-annotations',
            'flake8-django',
            'flake8-typing-imports',
        ]
        args: [
            "--max-line-length=88",
            "--extend-ignore=E203",
            "--docstring-convention=google",
            "--exclude=.git,__pycache__,build,dist"
        ]
        types: [python]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies: [
            'types-requests',
            'types-python-dateutil',
            'types-setuptools',
            'types-urllib3',
        ]
        args: [
            "--ignore-missing-imports",
            "--disallow-untyped-defs",
            "--disallow-incomplete-defs",
            "--check-untyped-defs",
            "--disallow-untyped-decorators",
            "--no-implicit-optional",
            "--warn-redundant-casts",
            "--warn-unused-ignores",
            "--warn-no-return",
            "--warn-unreachable",
            "--strict-optional",
        ]
        types: [python]

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.1
    hooks:
    -   id: ruff
        args: [--fix, --line-length=88]
        types: [python]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
        types: [python]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
    -   id: bandit
        args: ["-c", "pyproject.toml", "-r", "-ll"]
        additional_dependencies: ["bandit[toml]"]
        types: [python]

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.10.0
    hooks:
    -   id: commitizen
        stages: [commit-msg]

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
    -   id: prettier
        types: [javascript, jsx, ts, tsx, json, css, scss, markdown]
        additional_dependencies:
            - prettier@3.1.0
            - prettier-plugin-tailwindcss@0.5.11

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
    -   id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
            - eslint@8.56.0
            - eslint-config-prettier@9.1.0
            - eslint-plugin-prettier@5.1.3 