version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:3004"
    networks:
      - bleujs-network

  frontend:
    build: ./frontend
    ports:
      - "3000:8080"
    networks:
      - bleujs-network

networks:
  bleujs-network:
    driver: bridge
