version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    depends_on:
      - mongo

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - MONGODB_URI=mongodb://mongo:27017/bleujs
    depends_on:
      - mongo
