version: '3.8'

services:
  backend:
    build:
      target: development
    environment:
      NODE_ENV: development
      DEBUG: "true"
      ENABLE_SWAGGER: "true"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  core-engine:
    build:
      target: development
    environment:
      NODE_ENV: development
      DEBUG: "true"
    volumes:
      - ./core-engine:/app
      - /app/node_modules
    command: npm run dev

  eggs-generator:
    build:
      target: development
    environment:
      NODE_ENV: development
      DEBUG: "true"
    volumes:
      - ./eggs-generator:/app
      - /app/node_modules
    command: python -m debugpy --listen 0.0.0.0:5678 -m uvicorn main:app --reload --host 0.0.0.0

  frontend:
    build:
      target: development
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://localhost:4003
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

  mongo-express:
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://admin:pass@mongo:27017/
    depends_on:
      - mongo 