version: '3.8'

services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    container_name: bleujs-backend
    ports:
      - "3005:3005"
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    container_name: bleujs-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  mongo-data:
