[build]
  base = "frontend"
  command = "pnpm build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_APP_NAME = "Bleu.js Dashboard"
  VITE_API_URL = "https://api.bleujs.org"
  VITE_APP_URL = "https://bleujsdashbaord.netlify.app"
  VITE_TRIAL_DAYS = "30"
  VITE_CORE_MONTHLY_PRICE = "29"
  VITE_ENTERPRISE_MONTHLY_PRICE = "499"

[[redirects]]
  from = "/dashboard"
  to = "https://bleujsdashbaord.netlify.app"
  status = 200
  force = true

[[redirects]]
  from = "/dashboard/*"
  to = "https://bleujsdashbaord.netlify.app/:splat"
  status = 200
  force = true
  headers = {X-Frame-Options = "DENY", X-Content-Type-Options = "nosniff"}

[[headers]]
  for = "/dashboard/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/dashboard/assets/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Cache-Control = "public, max-age=0, must-revalidate"
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      X-Content-Type-Options = "nosniff"
      Referrer-Policy = "strict-origin-when-cross-origin"
      Content-Security-Policy = "default-src 'self' https://bleujsdashbaord.netlify.app https://api.bleujs.org; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://bleujsdashbaord.netlify.app; style-src 'self' 'unsafe-inline' https://bleujsdashbaord.netlify.app; img-src 'self' data: https:; font-src 'self' data: https:; connect-src 'self' https://api.bleujs.org https://bleujsdashbaord.netlify.app;"

[dev]
  framework = "vite"
  targetPort = 3000

[functions]
  directory = "netlify/functions" 