version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bleujs-backend
    restart: always
    ports:
      - '4003:4003'
    environment:
      - NODE_ENV=production
      - AI_API_URL=http://ai-service:8000/predict
      - MONGODB_URI=$(AWS_SECRETS_MANAGER_MONGODB_URI)
    depends_on:
      - ai-service
      - mongo
    secrets:
      - aws-secrets

  ai-service:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: bleujs-ai
    restart: always
    ports:
      - '8000:8000'
    environment:
      - PYTHONUNBUFFERED=1

  mongo:
    image: mongo:latest
    container_name: bleujs-mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=$(AWS_SECRETS_MANAGER_MONGODB_PASSWORD)
    volumes:
      - mongo_data:/data/db
    secrets:
      - aws-secrets

secrets:
  aws-secrets:
    external: true

volumes:
  mongo_data:
    driver: local

networks:
  default:
    name: bleujs-network
    external: true
