version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bleujs-backend
    restart: always
    ports:
      - '4003:4003'
    environment:
      - NODE_ENV=production
      - AI_API_URL=http://ai-service:8000/predict
      - MONGODB_URI=mongodb://mongo:27017/bleujs
    depends_on:
      - ai-service
      - mongo

  ai-service:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: bleujs-ai
    restart: always
    ports:
      - '8000:8000'
    environment:
      - PYTHONUNBUFFERED=1

networks:
  default:
    name: bleujs-network
    external: true
