[build]
  base = "frontend"
  command = "pnpm build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"
  VITE_APP_NAME = "Bleu.js Dashboard"
  VITE_API_URL = "https://api.bleujs.org"
  VITE_APP_URL = "https://bleujsdashbaord.netlify.app"
  VITE_TRIAL_DAYS = "30"
  VITE_CORE_MONTHLY_PRICE = "29"
  VITE_ENTERPRISE_MONTHLY_PRICE = "499"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-cache"
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval'; connect-src 'self' https: wss: blob:; img-src 'self' data: blob: https:; font-src 'self' data: https:;" 