version: '3.8'

services:
  quantum:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: pytest

  quantum-dev:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: /bin/bash
    stdin_open: true
    tty: true

  quantum-test:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: tox

  quantum-coverage:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: pytest --cov=quantum --cov-report=html
