AWSTemplateFormatVersion: '2010-09-09'
Description: 'Bleu.js IAM Roles and Policies'

Resources:
  BleuJSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bleujs-service-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonSESFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

  BleuJSInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: bleujs-instance-profile
      Roles:
        - Ref: BleuJSServiceRole

Outputs:
  ServiceRoleArn:
    Description: ARN of the Bleu.js service role
    Value:
      Fn::GetAtt: [BleuJSServiceRole, Arn]

  InstanceProfileArn:
    Description: ARN of the Bleu.js instance profile
    Value:
      Fn::GetAtt: [BleuJSInstanceProfile, Arn]
