#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

# Activate virtual environment if it exists
if [ -d "bleujs-env-py311" ]; then
    source bleujs-env-py311/bin/activate
fi

# Run Python tests
python -m pytest

# Run linting
python -m flake8
black . --check
isort . --check-only
